services:
  service1:
    build: ./service_1
    container_name: service1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://service1:8001"]
      interval: 30s
      timeout: 10s
      retries: 3

  service2:
    build: ./service_2
    container_name: service2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://service2:8002"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "9090:80"
    depends_on:
      - service1
      - service2